config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check

  root to: 'home#index'
  resources :warehouses, except: [:index]
  resources :suppliers, except: [:destroy]
  resources :product_models, only: [:index, :new, :create, :show]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member

    resources :order_items, only: [:new, :create]
  end
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier
  has_many :order_items
  has_many :orders, through: :order_items
  validates :name, :sku, presence: true
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @product_models = ProductModel.all
  end

  def new
    @product_model = ProductModel.new
    @suppliers = Supplier.all
  end

  def create
    product_model_params = params.require(:product_model).permit(:name, :weight, :height, :width, :depth, :sku, :supplier_id)
    @product_model = ProductModel.new(product_model_params)

    if @product_model.save
      redirect_to @product_model, notice: 'Modelo de produto cadastrado com sucesso'
    else
      @suppliers = Supplier.all
      flash.now[:notice] = 'Não foi possível cadastrar o modelo de produto'
      render 'new'
    end
  end

  def show
    @product_model = ProductModel.find(params[:id])
  end
end

app/views/product_models/index.html.erb
<h1>Modelos de Produtos</h1>

<p><%= link_to 'Cadastrar Novo', new_product_model_path %></p>

<% if @product_models.any? %>
  <% @product_models.each do |pm| %>
    <div>
      <h2><%= pm.name %></h2>

      <dl>
        <dt><%= ProductModel.human_attribute_name(:supplier_id) %>: </dt>
        <dd><%= pm.supplier.brand_name %></dd>
        <dt><%= ProductModel.human_attribute_name(:sku) %>: </dt>
        <dd><%= pm.sku %></dd>
      </dl>
    </div>
  <% end %>
<% else %>
  <p>Nenhum modelo de produto cadastrado</p>
<% end %>

app/views/product_models/new.html.erb
<h1>Cadastrar Novo Modelo de Produto</h1>

<%= form_with model: @product_model do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :weight %>
    <%= f.number_field :weight %>
  </div>
  <div>
    <%= f.label :height %>
    <%= f.number_field :height %>
  </div>
  <div>
    <%= f.label :width %>
    <%= f.number_field :width %>
  </div>
  <div>
    <%= f.label :depth %>
    <%= f.number_field :depth %>
  </div>
  <div>
    <%= f.label :sku %>
    <%= f.text_field :sku %>
  </div>
  <div>
    <%= f.label :supplier_id %>
    <%= f.collection_select :supplier_id, @suppliers, :id, :brand_name %>
  </div>

  <%= f.submit 'Enviar' %>
<% end %>

app/views/product_models/show.html.erb
<h1>Informações sobre <%= @product_model.sku %></h1>

<dl>
  <dt><%= ProductModel.human_attribute_name(:name) %>: </dt>
  <dd><%= @product_model.name %></dd>
  <dt><%= ProductModel.human_attribute_name(:sku) %>: </dt>
  <dd><%= @product_model.sku %></dd>
  <dt><%= ProductModel.human_attribute_name(:weight) %>: </dt>
  <dd><%= @product_model.weight %>g</dd>
  <dt>Dimensões: </dt>
  <dd><%= @product_model.height %>cm x <%= @product_model.width %>cm x <%= @product_model.depth %>cm</dd>
  <dt><%= ProductModel.human_attribute_name(:supplier_id) %>: </dt>
  <dd><%= @product_model.supplier.brand_name %></dd>
</dl>