config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check

  root to: 'home#index'
  resources :warehouses, except: [:index]
  resources :suppliers, except: [:destroy]
  resources :product_models, only: [:index, :new, :create, :show]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member

    resources :order_items, only: [:new, :create]
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :corporate_name, :brand_name, :registration_number, :full_address,
            :city, :state, :email, presence: true
  has_many :product_models
  has_many :orders
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: [:show, :edit, :update]

  def index
    @suppliers = Supplier.all
  end

  def show; end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)

    if @supplier.save
      redirect_to @supplier, notice: 'Fornecedor criado com sucesso'
    else
      flash.now[:notice] = 'Fornecedor não cadastrado'
      render 'new'
    end
  end

  def edit; end

  def update
    if @supplier.update(supplier_params)
      redirect_to @supplier, notice: 'Fornecedor atualizado com sucesso'
    else
      flash.now[:notice] = 'Não foi possível atualizar fornecedor'
      render 'edit'
    end
  end

  private

  def set_supplier
    @supplier = Supplier.find(params[:id])
  end

  def supplier_params
    params.require(:supplier).permit(:corporate_name, :brand_name,
                                    :registration_number,:full_address, :city,
                                    :state, :email)
  end
end

app/views/suppliers/_form.html.erb
<%= form_with model: @supplier do |f| %>
  <div>
    <%= f.label :corporate_name %>
    <%= f.text_field :corporate_name %>
  </div>
  <div>
    <%= f.label :brand_name %>
    <%= f.text_field :brand_name %>
  </div>
  <div>
    <%= f.label :registration_number %>
    <%= f.text_field :registration_number %>
  </div>
  <div>
    <%= f.label :full_address %>
    <%= f.text_field :full_address %>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <%= f.submit %>
<% end %>

app/views/suppliers/edit.html.erb
<h1>Editar Fornecedor</h1>

<%= render 'form' %>

app/views/suppliers/index.html.erb
<h1>Lista de Fornecedores</h1>

<%= link_to 'Criar Fornecedor', new_supplier_path %>

<% if @suppliers.any? %>
  <table>
    <thead>
      <tr>
        <th>Empresa</th>
        <th>Localização</th>
      </tr>
    </thead>
    <tbody>
      <% @suppliers.each do |supplier| %>
        <tr>
          <td><%= link_to supplier.brand_name, supplier %></td>
          <td><%= supplier.city %> - <%= supplier.state %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Não existem fornecedores cadastrados</p>
<% end %>

<div>
  <%= link_to 'Voltar', root_path %>
</div>

app/views/suppliers/new.html.erb
<h1>Novo Fornecedor</h1>

<% if @supplier.errors.any? %>
  <dl>
    <% @supplier.errors.full_messages.each do |msg| %>
      <dd><%= msg %></dd>
    <% end %>
  </dl>
<% end %>

<%= render 'form' %>

app/views/suppliers/show.html.erb
<h1>Informações sobre <%= @supplier.brand_name %></h1>

<dl>
  <dd>
    <strong><%= Supplier.human_attribute_name(:corporate_name) %>:</strong> 
    <%= @supplier.corporate_name %>
  </dd>
  <dd>
    <strong><%= Supplier.human_attribute_name(:brand_name) %>:</strong> 
    <%= @supplier.brand_name %>
  </dd>
  <dd>
    <strong><%= Supplier.human_attribute_name(:registration_number) %>:</strong> 
    <%= @supplier.registration_number %>
  </dd>
  <dd>
    <strong><%= Supplier.human_attribute_name(:full_address) %>:</strong> 
    <%= @supplier.full_address %>. 
    <%= @supplier.city %> - <%= @supplier.state %>
  </dd>
  <dd>
    <strong><%= Supplier.human_attribute_name(:email) %>:</strong> 
    <%= @supplier.email %>
  </dd>
</dl>


<div>
  <%= link_to 'Editar', edit_supplier_path(@supplier.id) %>
  <%= link_to 'Voltar', suppliers_path %>
</div>