config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check

  root to: 'home#index'
  resources :warehouses, except: [:index]
  resources :suppliers, except: [:destroy]
  resources :product_models, only: [:index, :new, :create, :show]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member

    resources :order_items, only: [:new, :create]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <%= link_to root_path do %>
        <h1>Galpões & Estoque</h1>
      <% end %>
      <nav>
        <%= link_to 'Fornecedores', suppliers_path %> |
        <%= link_to 'Modelos de Produtos', product_models_path %> |
        <%= link_to 'Registrar Pedido', new_order_path %> |
        <%= link_to 'Meus Pedidos', orders_path  %>
        <% unless user_signed_in? %>
          <%= link_to 'Entrar', new_user_session_path %>
        <% else %>
          <%= form_with(url: search_orders_path, method: :get) do |f| %>
            <%= f.label :query, 'Buscar Pedido' %>
            <%= f.text_field :query %>
            <%= f.submit 'Buscar' %>
          <% end %>
          |
          <%= button_to 'Sair', destroy_user_session_path, method: :delete %> |
          <%= current_user.description %>
        <% end %> 

      </nav>
    </header>
    <main>
      <div>
        <%= notice %>
        <%= alert %>
      </div> 
      <%= yield %>
    </main>
  </body>
</html>